### ISSUE TITLE
[Discuss] Commit Message

### ISSUE THREAD

**Issue by wenzong** [juwai/style-guide#10]
Currently we only force everyone add JIRA story number at the beginning of the commit message.

For a good commit message, I think we could improve in several aspects:

## Content

+ First, suggest try to use `git commit` instead of ~~`git commit -a`~~ `git commit -m`, which will open a new editor
+ Put a title to explain what you are doing in this commit
+ Put more descriptions in the new paragraph

We could have a look at @arkhi 's commit message: https://github.com/juwai/juwai-admin/pull/396/commits

And you will notice that every commit have a lot of details, which is good for us to understand what he has done in this PR.

Also, it's a good place to record our effort in these commits, then when you create the PR, you can easily summarize all your work.

## Sort commits

Sometimes we have a lot of commits in one PR, and some of the commits is just  one or two line change, doesn't have a lot of meaning.

Since we are using Fork-PR mode, I suggest before we open the PR, try to re-organize our commits, just leave the useful commit point there.

For more information, please ref to ~~https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History~~ https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits

**Comment by imlazyone** [comment]
> First, suggest try to use git commit instead of git commit -a, which will open a new editor
Should be git commit -a**m**? I think `git commit -a` will also open the editor

**Comment by wenzong** [comment]
@imlazyone sorry `git commit -m`

**Comment by arkhi** [comment]
I usually write my commit messages like this: `[JA-xx] Verb complement.` or `[JA-xx] Verb complement:`, depending on if the commit is a simple action or if it has more details.

I saw @diartyz writing the “JA” part in lowercase, and my lazy side actually like that more as it’s simply easier to type while conveying the same information.

So my take for a template would be:

`[ja-123] Rename all occurrences of “toto” to “tata”.`
or 
```markdown
[ja-456] Finish implementing RWD in juwai.com:

* Import all less files into main app.less.
* Replace Bootstrap by custom inline-block grid.
* Optimize all images.
* […]
```
@wenzong: About squashing, although I’m not used to it at all and I don’t have anything against, I thought we’re avoiding re–writing history…

**Comment by wenzong** [comment]
@arkhi I am suggesting that we could re-write the history on your fork/branch

re-write history make the commits clearer and more meaningful. and since it's only on your own fork/branch, it doesn't hurt anything, unless someone is collaborating on your fork/branch.

**Comment by arkhi** [comment]
@wenzong: Welcome back! We missed you. :)

OK啦. My lazy side doesn’t feel the necessity for it, and I usually like to (although not often do) keep commits into compartmented actions. But if the majority wants to squash, I’ll squash too.

**Comment by wenzong** [comment]
@juwai/all 

I think this document illustrate my point more clear: [Keeping Commit Histories Clean](https://www.reviewboard.org/docs/codebase/dev/git/clean-commits/)

I am not talking about the format or push everyone follow the same rule, just think it is a better developing habit :)

**Comment by imlazyone** [comment]
I second this.

If no one else has any objections, we can add a file in the repo for commit message guide.

**Comment by imlazyone** [comment]
created here: https://github.com/juwai/style-guide/blob/master/commit-message.md
