### ISSUE TITLE
Have “options” as the sole argument in JS functions

### ISSUE THREAD

**Issue by arkhi** [juwai/style-guide#13]
To avoid having to put arguments in a specific order when creating JS functions, can we use a default `options` arguments?

This way, we don’t have to [specify `undefined` if the function as many arguments](https://github.com/juwai/juwai-admin/blob/7b36fe5613554c8ca3709de59cee03fcb74a3627/public/js/group/products.js#L11) and we just want to define the last one.

@juwai/all: What do you guys think?

```js
someFunction( oneArgument, TwoArguments );
```
vs
```js
someFunctionWithMoreThanTwoArgument({
    'some': 'argument',
    'with': 'some',
    'other': 'argument',
    'in': 'whatever order',
    'it': 'doesn’t matter'
});
```

**Comment by HouCoder** [comment]
```
JW.updateCart( {
    'id': 11312,
    'userName': 'XXX'
} )
```
You mean call a function and pass arguments like this?

**Comment by arkhi** [comment]
Exactly, I’ll update to show this, thanks!

**Comment by HouCoder** [comment]
:+1:

**Comment by arkhi** [comment]
Documented in this file: https://github.com/juwai/style-guide/blob/master/language-javascript.md#be-more-flexible.
