### ISSUE TITLE
`name` attribute in html tags

### ISSUE THREAD

**Issue by arkhi** [juwai/style-guide#17]
While following idiomatic style–guides, could we have the `name` attribute of form controls right after the `id` attribute, before the `data` attribute?

`name` and `id` are often related and I think it would be good to keep them close to each other. This would lead to something like this:

```html
<input class="location" id="galaxy-name" name="galaxy[name]"
    data-id="123456789"
    placeholder="Which galaxy does your world belong to?"
    value="Milky way"
>
```

@juwai/all: What’s your take on this?

**Comment by HouCoder** [comment]
ok, good for me

**Comment by imlazyone** [comment]
sure :+1: 

BTW I think we should not ref private repos from this public repo.

**Comment by arkhi** [comment]
More than a month has passed, I will move this to the style–guides.
