### ISSUE TITLE
Simplify command selection in README

### ISSUE THREAD

**Issue by arkhi** [juwai/style-guide#19]
Triple–clicking on a paragraph can select the whole paragraph. So this can be very useful to select commands to run in the README files.

```md
Try to triple–click me to select the whole line.
```

Unfortunately, adding a `$` at the start of the line renders this more complicated:

```bash
$ echo 'triple–select me, then copy, paste, and delete the `$` at the start of the line.'
```
Can we avoid this popular `$` in code examples or README files?

**Comment by arkhi** [comment]
@juwai/all: What’s your take on it?

**Comment by tjoelsson** [comment]
I believe the $ implies executing on command line.

**Comment by tjoelsson** [comment]
Actually it also implies executing without `sudo`. If you need root privileges to execute the command there is usually a `#` in front.

**Comment by wenzong** [comment]
I personally agree with @tjoelsson 

but I also heard that if you have multiple lines of command, and copy-paste them all, then shell would run them in order, which is also convenient

but I think `$` indicate this is a command, not description, which is really helpful for me to understand the README

**Comment by imlazyone** [comment]
I think it's ok to remove the `$` if you didn't clearly state this needs a root privilege.

But also, I feel the downside `$` or `#` brought us (can't use triple click to select the whole line) is negligible...

I don't think we need to make a rule for this.

**Comment by xinningsu** [comment]
The current read me is fine. it does't bother me at all.

**Comment by arkhi** [comment]
I can’t wait to see command lines starting with `$` in README files, even though they need to be run as root…
