### ISSUE TITLE
python import

### ISSUE THREAD

**Issue by liangshan** [juwai/style-guide#4]
We discussed a lot about whether to use relative.

Our guideline basically based on PEP8, but I made a lot of change from recommended to required, because i want to make it more clearly. 

Let's make a vote.

**Comment by liangshan** [comment]
Absolute import only  +1

**Comment by JackieMa000** [comment]
I think this should depends on certain situation. We should not limit it.  Absolute or relative should be decided by the person who writing that piece of code.

**Comment by liangshan** [comment]
Rules should be simple and clear. Let's say we can use explicit relative import, then we have to list all the situations when could use it and when not.

http://stackoverflow.com/questions/12738889/when-or-why-to-use-relative-imports-in-python

> Several use cases were presented, the most important of which is being able to rearrange the structure of large packages without having to edit sub-packages. In addition, a module inside a package can't  easily import itself without relative imports.

I don't think we will have __large packages__ or __complex package__ . So i suggest keep using absolute import,  if someone want to use relative import, he can explain to all of us and if there is a very strong necessary, i think we can accept the extreme exceptions.

**Comment by JackieMa000** [comment]
This package is already complex and large. Plus this is just the beginning of the rpc project. And this package will be more and more big and complex.

```
 jw.rpc.service.location.regions
```

**Comment by liangshan** [comment]
This example just shows maybe we don't need `service` level.

```
from jw.rpc.location import regions
```

When you have a deep import, just think about why we need that.

Actually, my point is  "Let's say we can use explicit relative import, then we have to list all the situations when could use it and when not."

So @JackieMa000, if you can give a list that when could use explicit relative import, and how to use it, i will totally agree with that.

**Comment by liangshan** [comment]
I found one situation that maybe could use explicit relative import, which is importing the module from same level, if the module is too deep in the repository.

Most of the style guideline is for human to read, not for the compiler. So i think one `.` is quite easy to understand and to locate the imported module.

 I'm quite sure not to use three `.` like `import ...foo` to import modules, but not very sure that whether or not to use `..` to import parent level modules.

**Comment by JackieMa000** [comment]
And for unit tests, that makes more sense if we use relative import.

**Comment by liangshan** [comment]
OK, if everyone agree with that we can use explicit relative import to import module in the same level. I will close the issue and update the doc.

@JackieMa000  can u give me an example when using that in the unit tests?

**Comment by liangshan** [comment]
The conclusion is **we can use explicit relative import to import module in the same level**.
