### ISSUE TITLE
Deadlinks in the documentation.

### ISSUE THREAD

**Issue by dppereyra** [juwai/style-guide#41]
1. If I click the link **timely feedback** on the [Workflow Issue Priority page] (https://github.com/juwai/style-guide/blob/master/workflow-issue-priority.md)
    1. the browser returns 404.

2. If I click the links about the workflows for **Jira, Meeting Rooms, Slack** on the [README.md](https://github.com/juwai/style-guide/blob/master/README.md)
    2. the browser returns 404.

### Expected Workflow

1. If I click the link **timely feedback** on the [Workflow Issue Priority page] (https://github.com/juwai/style-guide/blob/master/workflow-issue-priority.md)
    1. I am sent to the page pertaining about timely feedback.

2. If I click the links about the workflows for **Jira, Meeting Rooms, Slack** on the [README.md](https://github.com/juwai/style-guide/blob/master/README.md)
    2. I am sent to the page pertaining to the specified workflow.

### Resources

Item 1 URL: https://github.com/juwai/style-guide/blob/master/workflow-issue-priority.md
Item 2 URL: https://github.com/juwai/style-guide/blob/master/README.md

**Comment by arkhi** [comment]
What’s missing to this issue for it to be closed?

**Comment by dppereyra** [comment]
I think this is now resolved. Closing this issue.
