### ISSUE TITLE
Is that necessary to quote all JavaScript keys?

### ISSUE THREAD

**Issue by HouCoder** [juwai/style-guide#57]
Currently we are quoting JavaScript key names in our style-guide: https://github.com/juwai/style-guide/blob/master/language-javascript.md#fix-errors-early

In a certain situation it make sense, like:

```js
var user = {

    // Invalid identifier name
    'company-address': 'Shanghai',

    // Reserved word
    'class': 'o-img'
}
```

But they were very rare, I felt annoying during the developing, what you think? @juwai/consumer-all @juwai/industry-all

**Comment by arkhi** [comment]
JS object properties are quoted to avoid confusion for devs coming from other coding languages.

This was introduced after @tjoelsson left a comment in another repository. The specific case that was discussed was this one:

```js
var thing = {
    $property: $( '.selector' );
};
```

Related PR: https://github.com/juwai/style-guide/pull/44

@tjoelsson might explain better.

**Comment by tjoelsson** [comment]
In JavaScript `$property` is simply used as a key name, but for example in PHP, `$property` would be evaluated to the variable contents. This is very confusing, don't you think? That's why we decided to quote the keys.

**Comment by tjoelsson** [comment]
Another solution would be to not use $ in variable or key names in JavaScript, but I know you guys like to do that.

**Comment by KixPanganiban** [comment]
Imho, only quote keys if they are invalid identifiers (eg containing `$` or `-`), like @HouCoder said, and described in the popular [Airbnb JS style guide](https://github.com/airbnb/javascript#objects--quoted-props). Other than that, we probably shouldn't be quoting them and start to avoid using `$` in JS vars. In some frameworks like Angular, `$` is reserved for [scoping](https://docs.angularjs.org/guide/scope). I know we don't use Angular, but won't it be better if we adapt to usual industry practices?

**Comment by vijaykumarjuwai** [comment]
I really don't like the use of `$` for var names in JS. I think this needs to change.

**Comment by HouCoder** [comment]
@vijaykumarjuwai

`$` prefix has it's advantage, it indicates it's an jQuery object, standards variable names,  consider the following code in JavaScript:

```js
var userName = 'Juwai';
var $userName = $( 'c-user__name' );
```
What's your suggestion to improve the readability for avoiding confusing?

@KixPanganiban 

Yes, it makes sense in Angular.js, it I took a closer in Airbnb's style-guide, they also encourage to use `$`  prefix to name an jQuery object: https://github.com/airbnb/javascript#jquery

**Comment by arkhi** [comment]
@KixPanganiban: The use of `$` is an [usual industry practice](http://stackoverflow.com/questions/205853/why-would-a-javascript-variable-start-with-a-dollar-sign). It’s even an [available rule in JSCS](http://jscs.info/rule/requireDollarBeforejQueryAssignment). 
@vijaykumarjuwai: Better explain why; personal feelings have less weight than proper arguments.

Some more explanations about quotes for objetct properties: http://eslint.org/docs/rules/quote-props

**Comment by KixPanganiban** [comment]
Ah, I see. So we're only prefixing `$` to jQuery objects? In that case, I have no objections. My initial understanding was that we were merely prefixing `$` arbitrarily.

**Comment by HouCoder** [comment]
> In JavaScript $property is simply used as a key name, but for example in PHP, $property would be evaluated to the variable contents.

Only if you specifically use PHP template delimiter in JavaScript:

e.g:

In native PHP
```php
<html>
    <head>
        <title>PHP Test</title>
        <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    </head>
    <body>
        <?php
        $className = '.c-user';
        $content = 'Hello User!';
        ?>

        $( '<?php echo $className; ?>' ).text( '<?php echo $content ?>' );
    </body>
</html>
```

**Comment by vijaykumarjuwai** [comment]
@arkhi I think I am biased on this because I have used Angular extensively in my previous job and in Angular `$` was a key character when referring to the scope. I did read the [usual industry practice](http://stackoverflow.com/questions/205853/why-would-a-javascript-variable-start-with-a-dollar-sign) and there are arguments there for both sides. 

If it is referring to an object its totally fine though.

**Comment by monochrome-yeh** [comment]
I think this issue is depending on how we use closure or how we encapsulate modules,
we would use `quote/double quote` for that, if we always want to write javascript directly in PHP template.

**Comment by monochrome-yeh** [comment]
BTW you could also use this blade function to avoid write javascript with PHP

FYI: https://laravel.com/docs/5.3/blade#stacks

**Comment by tjoelsson** [comment]
@tonni I thought we were talking specifically about object/array key names. My point was that people who write PHP code and JavaScript code (not necessarily in the same file) would have an easier time reading other's code if we quote the key names or avoid using $ in key names.

**Comment by monochrome-yeh** [comment]
@juwai/consumer-all @juwai/industry-all, don't forget, we aren't using any front-end linter for `template files`, therefore we can't detect code style at the moment.

**Comment by HouCoder** [comment]
@tjoelsson 

I agree with your point in a certain degree, but avoiding `$` in JavaScript is not a good practice since jQuery has been heavily used in our projects.

**Comment by tjoelsson** [comment]
I'm not saying to avoid it completely. Just in key names.

**Comment by HouCoder** [comment]
Different language has different syntax, and PHP developer already familiar with JavaScript syntax,  I don't think it's a problem, I vote for not quoting key names unless it's a Invalid identifier name or reserved word.

I'll create a PR for this issue, and let rest front-end developer decide.

Note: Airbnb's JavaScript standard talked about why don't need quote properties names, and they explained why: https://github.com/airbnb/javascript#objects--quoted-props

**Comment by tjoelsson** [comment]
What about $ in key names?

**Comment by monochrome-yeh** [comment]
@tjoelsson , @HouCoder 
> What about $ in key names? I don't see anyone recommending this practice.
Should we really agree mix PHP and javascript in template file?

e.g
```php
$(function(){
    alert('{{ $helloWorld }}');
})();
```

**Comment by tjoelsson** [comment]
I'm not talking about mixing javascript and php. Just asking if we can avoid using $ in key names in javascript. Like Fabien's example:

```javascript
var thing = {
    $property: $( '.selector' );
};
```

**Comment by monochrome-yeh** [comment]
I'm concerned which languages/frameworks do we use for javascript.
I prefer use `$` in laravel/PHP and native javascript,
but I'm not sure for the others.

**Comment by HouCoder** [comment]
@tjoelsson using `$` in key names in javascript makes sense for me, `$` and `_` are valid key names, according to the [Airbnb's recommendation](https://github.com/airbnb/javascript#objects--quoted-props): 

> Only quote properties that are invalid identifiers.

Thus no need to quote them, they are valid key names.

For further reading: https://mathiasbynens.be/notes/javascript-identifiers

**Comment by tjoelsson** [comment]
I'm not saying they are not valid key names. I'm just saying it's confusing because in PHP code, using $property as a key name would be handled differently than in javascript. When you read and write multiple languages it's easy to get confused. Especially when the syntax is similar. That's the reason we had this in style-guide. My suggestion if you want to remove the quotes is just to not use $ in key names. I don't think that's a big problem.

**Comment by tjoelsson** [comment]
I'm not going to argue this as I'm probably not going to touch that javascript any time soon. If you need to use $ in key names for some reason, then that's fine with me.

**Comment by monochrome-yeh** [comment]
there are 2 issues here,
- how to avoid difficultly read/write with jQuery symbol in PHP
    - we might try to separate 2 languages as possible.
    - we would strictly use global definition, if we really want to passed the js variables from PHP
    - FYI: https://laravel.com/docs/5.3/blade#stacks
- should we use `$` with quotes in javascript key name
