### ISSUE TITLE
Considering migrating to airbnb/javascript style guide.

### ISSUE THREAD

**Issue by HouCoder** [juwai/style-guide#60]
As ES6 grows up, and we started to use it in several projects, but our current JavaScript style guide - [necolas/idiomatic-js](https://github.com/necolas/idiomatic-js) seems abandoned, and [necolas/idiomatic-js](https://github.com/necolas/idiomatic-js)'s upstream [rwaldron/idiomatic.js](https://github.com/necolas/idiomatic-js) doesn't provide ES6 syntax style guide.

I'm wondering if we could switch to the [airbnb/javascript](https://github.com/airbnb/javascript), which is well maintained and they also provided config files for linting tools.

**Comment by imlazyone** [comment]
upvote 👍

**Comment by HouCoder** [comment]
Closing this issue, since I made a pull request for this issue: https://github.com/juwai/style-guide/pull/61
