### ISSUE TITLE
Increase line length soft limit to 120

### ISSUE THREAD

**Issue by agirivera** [juwai/style-guide#62]
https://github.com/juwai/style-guide/blob/master/language-python.md#maximum-line-length

Can we increase the soft limit for prettier code and minimize the time spent trying to decide how we can _acceptably_ break a line?

Relevant material:
Raymond Hettinger: Beyond PEP8
https://youtu.be/wf-BqAjZb8M

@tjoelsson @steffbucag @mark-juwai @fredr-juwai

**Comment by tjoelsson** [comment]
Do you have an example of where code would be prettier with longer lines? I personally rarely have this problem.

**Comment by agirivera** [comment]
From:

```
        if source.name != target.name:
            aliases = self.remap_aliases(source, target,
                                         'sublocality', verbose)

            self.get_or_create_alias(source.name, target.name,
                                     'sublocality', commit=False)

        Sublocality.query.filter_by(id=source.id).\
            delete(synchronize_session=False)
        db.session.commit()
```

To:

```
        if source.name != target.name:
            aliases = self.remap_aliases(source, target, 'sublocality', verbose)
            self.get_or_create_alias(source.name, target.name, 'sublocality', commit=False)

        Sublocality.query.filter_by(id=source.id).delete(synchronize_session=False)
        db.session.commit()
```

**Comment by agirivera** [comment]
From:

```
        except etree.XMLSyntaxError as e:
            log.exception(e)
            message = 'XML file {} not well-formed: {}'.format(xml_file,
                                                               str(e))
```

To:

```
        except etree.XMLSyntaxError as e:
            log.exception(e)
            message = 'XML file {} not well-formed: {}'.format(xml_file, str(e))
```

**Comment by tjoelsson** [comment]
@steffbucag @mark-juwai what do you guys think? is it easier to read?

I prefer short lines. Feels easier to read it that way. Maybe just because I'm used to it.

**Comment by agirivera** [comment]
> I prefer short lines

I do too, but there are scenarios where we have long variable names and method names already on the code base that make it hard to fit on 79-char line.

This is related by the way: https://github.com/juwai/in-house/issues/109

**Comment by mark-juwai** [comment]
I don't care much about it.
Will `pep8 ./src ./tests` complain long lines in [travis](https://github.com/juwai/juwai-rpc/blob/master/.travis.yml#L16)?

**Comment by steffbucag** [comment]
I agree that we need to  increase the line length. 

My concern is that there are lines that are 80-ish in length. We have to break the line to meet pep8 standard.

For example:

![screen shot 2017-02-28 at 09 39 14](https://cloud.githubusercontent.com/assets/17819123/23387815/d7dc67c8-fd99-11e6-8d3a-5de681905d0e.png)

To follow pep8 standard, we change this to
```
            r = requests.get(url, headers={'user-agent': user_agent},
                             timeout=60)

OR

            r = requests.get(url, 
                             headers={'user-agent': user_agent},
                             timeout=60)
                             
```

I think it would be more readable if this code is just in a single line. 

However, I'm thinking 120 might be too long.

**Comment by agirivera** [comment]
> Will pep8 ./src ./tests complain long lines in travis?

@mark-juwai Yes, unless you modify it with `--max-line-length=n`

> My concern is that there are lines that are 80-ish in length

@steffbucag We can start at 90, then review after a month if we still need to increase.

**Comment by mark-juwai** [comment]
If we decide to increase, I would prefer 120, to be consistent with [PSR2](http://www.php-fig.org/psr/psr-2/). It's soft limit, you can always write short lines if you like.

**Comment by agirivera** [comment]
The masses have [spoken](https://juwai.slack.com/archives/G4BU7PQTY/p1488248625000002) and we are retaining the line-length at 79.
